### ISSUE TITLE
Migrate admin api from php to python

### ISSUE THREAD

**Issue by kldavis4** [ConnectBox/connectbox-pi#111]

**Comment by portablejim** [comment]
Some work I have done on it https://github.com/portablejim/connectbox-pi/tree/python_admin

**Comment by edwinsteele** [comment]
Hi @portablejim , thanks for your work on this, it looks great. We’ll need to break the commit up into a few PRs. Let’s start with the ansible bump (please PR that at your convenience) and over the next week I’ll spend some time to bring the other users of the connectbox virtualenv across to python3 (@kldavis4 this will be chat and captive portal). I’ve wanted to move these across to py3 for a while, and now I have an excuse :-) ). At that point we can get going on integrating your work and bid farewell to our php implementation. I’m travelling over this next week so my access may be spotty but we’ll get there.
