### ISSUE TITLE
Filter standard operating system folders on USB from icon interface

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#118]
Originally mentioned by @algebur . A windows-formatted USB key has a folder called `System Volume Information` which shows in the interface. We should filter this out, as it’ll never have any end-user managed files.

Similarly for `.DS_Store` directories that might be present on USB keys used on a Mac.

**Comment by GeoDirk** [comment]
Couple of standard windows ones:

-rwxr-xr-x 1 root root    16 May 26  2016 **AUTORUN.INF***
drwxr-xr-x 2 root root 65536 May 13  2016 **System Volume Information**/

Not sure why the autorun one ends in a *

**Comment by edwinsteele** [comment]
Bumping from 25-unit pilot milestone after discussion with Dirk (Kelly’s rebuilding this area at the moment, and we can make it a “known issue” for the pilot)

**Comment by edwinsteele** [comment]
Fixed by #152
