### ISSUE TITLE
Disable new “consistent naming” of wlan interfaces

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#122]
Ubuntu names wlan interfaces based on the MAC of the adapter. This breaks config like `hostapd.conf` where we need to provide the wlan interface name. We can revert to the old naming with a symlink under /etc ( @matheweis knows what) or using some boot params per: https://github.com/ConnectBox/wifi-test-framework/blob/master/ansible/roles/setup-system/tasks/main.yml#L25

I don’t mind which one we use.

**Comment by matheweis** [comment]
ln -s /dev/null /etc/udev/rules.d/80-net-setup-link.rules && reboot
