### ISSUE TITLE
Internal NEO USB ports stop working when kernel is updated

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#149]
a `/boot/dtb` directory is created on each kernel update, however we create an overlay in that directory on our initial run in order to activate the internal USB ports. It’s hard to create that overlay on each kernel update, so we have a problem.

Thoughts:
* blacklist the kernel from being updated
* get the overlay added upstream. Even though the sun8i setup is shared with lots of boards, it may be accepted because the overlays aren’t activated without a line in armbianEnv.txt.

**Comment by matheweis** [comment]
Solved w/easy fix to #150 imho, but will give it some thought.

**Comment by edwinsteele** [comment]
Given the last step of our playbook is to update packages, I don't think #150 will solve this.

I deliberately put the overlay creation at the start of the playbook, so at worst we need to have one reboot that takes care of all the rebooty things like interface naming and overlay creation. This issue happens when the base image doesn't contain the latest kernel package, because the last step of our playbook updates it.

**Comment by matheweis** [comment]
Can't we just run it again though?

**Comment by edwinsteele** [comment]
Sure, but reboots increase the time and complexity of a deployment run so I think we should work hard to avoid them.

**Comment by edwinsteele** [comment]
The overlays for usbhost0, 2 and 3 were added in https://github.com/armbian/build/commit/0630d4dcd9f1f7e995d9f7bca7d6a952ba5ce92c#diff-7a324c1a1d17511d2a3728f2cb90d449 . There’s no indication or comment on why usbhost1 was omitted.

**Comment by edwinsteele** [comment]
The next step is to confirm that our apt update services (https://github.com/ConnectBox/connectbox-pi/blob/master/ansible/group_vars/armbian#L4) are indeed stopped and disabled when a device is booted from one of our images. Ansible does disable them, but I suspect that a first-run type service is re-enabling them.
