### ISSUE TITLE
Admin interface allows invalid channel to be set (disables the AP)

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#165]
Not all channels are available, depending on the regulatory domain. The admin interface allows channels to be set that prevent the AP from starting (even though the interface is up from the OS perspective).

e.g. Channel 12 is invalid in the 00 world regulatory domain (which we use right now, though this will change soon). If you set the channel to 12 in the admin interface, there’s no feedback, and it’s no longer possible to connect (on the back-end, the hostapd.conf has been updated, but hostapd refuses to start).

**Comment by kldavis4** [comment]
Interesting.. What's the best way to know what channels are valid?

**Comment by edwinsteele** [comment]
There’s a regulatory db that specifies the valid channels for each regulatory domain, but there also seems to be some chipsets that simply don’t support all the channels. Still working out how that fits together, and what we can support. Perhaps on the back-end, we can rollback the change if hostapd doesn’t start?

Will get back to you on how we can determine what’s valid.

**Comment by edwinsteele** [comment]
So the channel rules for the regulatory domain don't appear to tell the whole story, as there also appear to be constraints placed in the EEPROM of the wifi device. For example, with the reg domain set to AU, I should be able to setup an AP on channel 11, but the device prevents it.

I suggest we avoid client-side validation and make sure that we rollback the change to hostapd.conf if hostapd doesn't start. While it doesn't necessarily help the user in determining what's valid, we'll never brick the device.

(I'm avoiding client-side validation because a) it's hard to work out what is actually valid in the 2.4Ghz space, and b) when we start using 5Ghz channels the numbers are higher - and the interface shouldn't prevent someone from trying)

Sound ok?
--
Edwin Steele e: edwin@wordspeak.org w: https://wordspeak.org

**Comment by kldavis4** [comment]
Yep, sounds like a good plan

**Comment by edwinsteele** [comment]
I’ve not made progress on this, so a fallback is to constrain the channels to the intersection of those available in all reg-domains but turning the text field into a dropdown.
