### ISSUE TITLE
Python Shutdown Code

### ISSUE THREAD

**Issue by GeoDirk** [ConnectBox/connectbox-pi#192]
Complete code to monitor battery levels and deploy to ConnectBox in such a way that it starts on boot.

**Comment by edwinsteele** [comment]
@edwinsteele to take the battery level code, and integrate it using ansible. Will likely require a systemd service for running.

**Comment by GeoDirk** [comment]
This seems like a relatively simple way of getting the systemd service going for the Python script:

https://www.raspberrypi-spy.co.uk/2015/10/how-to-autorun-a-python-script-on-boot-using-systemd/

@edwinsteele Do you need me to write this function and you implement it in the Ansible code?
