### ISSUE TITLE
Expose device version in the admin interface

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#194]
Show the cal-ver that we use when we make our release

**Comment by GeoDirk** [comment]
It doesn't necessarily need to be a number or anything.  Perhaps just a text file like the /etc/debian_version type of format where we give it a code name.  Might make it easier to not have to worry about always changing out the number system with every build.

Just a thought.

**Comment by edwinsteele** [comment]
Duplicate of #240
