### ISSUE TITLE
Admin console About

### ISSUE THREAD

**Issue by kirkdwilson** [ConnectBox/connectbox-pi#200]
Unable to change about text in admin console

**Comment by edwinsteele** [comment]
The about text is not intended to be edited by a user, but we should link to the connectbox homepage and possibly the GitHub repository.

**Comment by GeoDirk** [comment]
Sounds like a plan.  Let's add in the two links: www.connectbox.technology and this GitHub link.

I think both Kirk and I are confusing this with being part of #185
