### ISSUE TITLE
Admin Console - Contact

### ISSUE THREAD

**Issue by kirkdwilson** [ConnectBox/connectbox-pi#201]
Unable to edit contact data in admin console

**Comment by edwinsteele** [comment]
The contact data field in the admin console adds no value - the administrator already knows the contact for the device, and we already plan to do #185 which will show it to users. This ticket, then, should be to remove the contact data area and menu item, and let #185 add it as a part of that work.

**Comment by GeoDirk** [comment]
Ah, yes I think both Kirk and I were under the impression that this was part of the #185 request and may will be.  For the 100 unit release, how about we take this field out of the Admin panel so we don't confuse others like Kirk and I were?
