### ISSUE TITLE
Admin - reports

### ISSUE THREAD

**Issue by kirkdwilson** [ConnectBox/connectbox-pi#202]
Not in screen readable format.  If the stats are going to be 'downloaded' then the format makes sense for further processing.  However, for screen reading this does not help.

**Comment by GeoDirk** [comment]
I think we are looking for a simple JSON to table view here.  But lets certainly keep the JSON dump so that the admin can do what Kirk is suggesting of downloading the data too.

**Comment by edwinsteele** [comment]
Fixed by https://github.com/ConnectBox/connectbox-pi/pull/208
