### ISSUE TITLE
Admin Panel: Banner Preview Enhancement

### ISSUE THREAD

**Issue by GeoDirk** [ConnectBox/connectbox-pi#209]
Was working though the latest build and checking out the new Admin panel.  Thus far, everything works well.  I did have a usability suggestion though.  As I was playing through the banner section, it would be nice to actually have a banner preview (see mockup image) after you hit the update button.  I found that I had to modify the banner, update, then go out to see what it looked like in the normal interface.  The preview window would let you verify your look while in the editor environment.

![image](https://user-images.githubusercontent.com/1356726/34327358-32aa9ee8-e8d3-11e7-912f-666bea8b08c0.png)

**Comment by kirkdwilson** [comment]
Panel window has been removed
