### ISSUE TITLE
Create link to admin in icon-only interface

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#211]
The admin area is important and needs to be discoverable. It isn’t as important as the chat function, so shouldn’t be given the same visibility, so let’s place a link (suggest a fa-cog icon) in a footer that’s a coloured div (no need to make it floating).

While it’s a little odd to be creating a footer for a single thing, we can probably use the footer area for other things once we see it in action.

**Comment by kldavis4** [comment]
I've added the footer (and made a few other ui tweaks).  I haven't published the changes yet. When you get a chance, pull down the latest commit and run locally to see how it looks (`yarn start`). (Note the admin link won't actually take you to the admin dashboard). Once it looks good, I'll publish a new version of the ui.

**Comment by edwinsteele** [comment]
Looks good, thanks. I have a slight preference for the icon being in the bottom right (it’s the least intrusive) but don’t feel strongly about it (leave it on the left if you’d like)

**Comment by kldavis4** [comment]
Ok, thanks for the review. I've moved the icon to the bottom right and published the updated ui

**Comment by edwinsteele** [comment]
Fixed by https://github.com/ConnectBox/connectbox-react-icon-client/commit/028210003c5d8395e31b64345a392730103aef17
