### ISSUE TITLE
Specify version for git checkout tasks

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#223]
default to master, but allows overriding so that we can rebuild an image based entirely on tags (at least for our codebase).

It’s also possible that some or all of the git checkouts will be replaced with native package invocations (pip with a git URL, npm with a git URL), so those should also allow tags.

**Comment by kirkdwilson** [comment]
Codebase determines the target hardware and adjusts accordingly

**Comment by glowingwire** [comment]
unsubscribe
