### ISSUE TITLE
Auto open index.htm or index.html file

### ISSUE THREAD

**Issue by kirkdwilson** [ConnectBox/connectbox-pi#225]
If a directory has an index.htm or index.html file it should be auto opened in the browser.  This allows for HTML applications and products to load automatically if contained in a folder.

If possible there should be a way to 'home' or back from the pages... but this can also be incorporated into the HTML applications or products.

**Comment by edwinsteele** [comment]
This is the behaviour for static-site mode, and is not possible for icon-only
