### ISSUE TITLE
Admin system actions report "not initiated" despite performing action

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#247]
All of the system functions in the new admin interface work correctly, but show a warning that implies that they didn't. Seen in iOS Safari and iOS firefox focus.

![1](https://user-images.githubusercontent.com/1515215/42202791-0f6b9718-7ee0-11e8-9b0f-4ac6e91e8f7f.jpg)

**Comment by kldavis4** [comment]
This should be fixed now. Please check and confirm.

**Comment by edwinsteele** [comment]
Fixed in https://github.com/ConnectBox/connectbox-react-icon-client/commit/4667cf02c6a3d0b55794553b6e0abade17a4e7dc
