### ISSUE TITLE
OH GOD I AM NOT GOOD AT COMPUTERS HOW DID THIS GET HERE!?

### ISSUE THREAD

**Issue by Ham549** [ConnectBox/connectbox-pi#303]
![Screenshot from 2020-03-28 18:09:52](https://user-images.githubusercontent.com/61761398/77835005-aa1a5a00-711f-11ea-9716-fc984f36091f.png)
What am I doing wrong? Also once done can I take the SD card out of the rp3 and put in in a rp0?

**Comment by Ham549** [comment]
I am only using my rp3 because it has Ethernet and the tut is for Ethernet only I plan to use a rp0 for the finished project.

**Comment by caroft** [comment]
I am struggling too...! for what I see in your screen capture : I would have decomment the second line where I think is your rp3 IP and maybe comment the first one
For me it worked with only this line beginning by 192.168.X.X
