### ISSUE TITLE
Create an easy way to move a file from a usb stick to a file that can be referenced within wordpress

### ISSUE THREAD

**Issue by montieroland** [ConnectBox/connectbox-pi#321]
Create an easy way to move a file from a usb stick to a file that can be referenced within wordpress

**Comment by montieroland** [comment]
:-)

**Comment by montieroland** [comment]
This would be really handy

**Comment by kirkdwilson** [comment]
This can be achieved by the front panel copy utility.  If you need it moved to another directory other than /media/usb0 then a script file can be added to the chron tab. or a slight modification to PxUSBm.py in /usr/local/connectbox/bin
