### ISSUE TITLE
Add option for external antenna

### ISSUE THREAD

**Issue by montieroland** [ConnectBox/connectbox-pi#322]
Add option for external antenna

**Comment by montieroland** [comment]
Maybe include spec for an matching extension cable (possibly 4-6 inches long)

**Comment by kirkdwilson** [comment]
montieroland: we can do this as a special request.  We have hardware in hand to do this.

**Comment by montieroland** [comment]
Great

**Comment by kirkdwilson** [comment]
closed issue
