### ISSUE TITLE
Provide 2D or 3D cad for PCBA 

### ISSUE THREAD

**Issue by montieroland** [ConnectBox/connectbox-pi#323]
Having the CAD files makes it easier to package the unit in a custom enclosure

**Comment by kirkdwilson** [comment]
I'll check into this.

**Comment by montieroland** [comment]
Morning,

Do you have a new release that I can install on my ConnectBox?

Montie

Montie Roland
***@***.***
Sanford, NC

A candle loses nothing by lighting another candle

Blog and Podcast - www.montie.com
Montie Gear - www.montiegear.com
Simply Us Farm - www.simplyusfarm.com

------- Original Message -------

**Comment by montieroland** [comment]
Thanks

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by kirkdwilson** [comment]
Dear Montie;

 

Please look at this release:

https://github.com/ConnectBox/connectbox-pi/releases/tag/v20220309.2.0

 


This is hot off the press and includes the new interface and admin console

 

Kirk

**Comment by montieroland** [comment]
Were you able to create a 3D cad file of the electrical assembly?  Or a drawing of the assembly?

**Comment by kirkdwilson** [comment]
Are you planning to put wordpress on it?

 

Kirk

**Comment by kirkdwilson** [comment]
Is this for the Connectbox Pi or the Connectbox NEO?

 

Kirk

**Comment by montieroland** [comment]
Yes

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by montieroland** [comment]
Whichever one you provided

Sent from ProtonMail mobile

-------- Original Message --------
