### ISSUE TITLE
Still need easer acess

### ISSUE THREAD

**Issue by Ham549** [ConnectBox/connectbox-pi#342]
Library Box another open source media platform is set up to automatically bring you to the main page as soon as you connect to the network. It would be nice if ConnectBox could do the same. Also, it would be nice to be able to leave out the most recent downloads and comment function. 

Having worked on the Librarybox project extensively,  a decision was made to add a captive portal.  This ensures we have better control over access.  One suggestion would be to use a QR code to guide the connection and main page.

**Comment by montieroland** [comment]
Agreed

Montie Roland
***@***.***
Sanford, NC

A candle loses nothing by lighting another candle

Blog and Podcast - www.montie.com
Montie Gear - www.montiegear.com
Simply Us Farm - www.simplyusfarm.com

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by Ham549** [comment]
It still doesn't seem to work, It would also be nice if there was a desktop included So instead of having to SSH into everything I can just use it as a standalone computer and transfer the file through USB. I had previously had a bill that had a desktop included And it made it very easy to add and remove content. Also would still like to know how to remove the chat function because it's out being able to monitor the connect box all the time I'd hate for somebody to leave something offensive on it.
