### ISSUE TITLE
"Indexing Data" message peristent forever at startup

### ISSUE THREAD

**Issue by montieroland** [ConnectBox/connectbox-pi#343]
I'm getting an "Indexing Data" message when I start up the unit running  the 20241011_armbian24.8.5.img.xz version.  Any suggestions?  

My suggestion is to wait.  One of the new features of collections is the Bility to download the entire collec6as a single zip file.  If it dosnt exist the system creates it on first run. Unfortunately the microPi is not a fast processor.   It can take time to create.  If it's created in another host system in the file then it faster.

**Comment by montieroland** [comment]
I'm running a connectbox P and all three lights are lit (yellow, orange, red)

**Comment by montieroland** [comment]
I'm able to connect the wifi of the box, but not able to connect to the gowifi.org site

**Comment by montieroland** [comment]
![Screenshot 2024-12-24 193637](https://github.com/user-attachments/assets/d1dcfa8d-792a-4bce-b2ba-27800645fc5c)

What else do you need?

**Comment by kirkdwilson** [comment]
It would appear that the connectbox is not transmitting correctly on your PC.  Can you show me the network screen

Kirk

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by montieroland** [comment]
Where is the network screen?

Montie Roland
***@***.***
Sanford, NC

A candle loses nothing by lighting another candle

Blog and Podcast - www.montie.com
Montie Gear - www.montiegear.com
Simply Us Farm - www.simplyusfarm.com

Sent from Proton Mail Android

-------- Original Message --------
