### ISSUE TITLE
Fix Android and Windows captive portal behaviour

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#41]
We don’t have any captive portal logic for Android or Windows (phone/desktop) so I’m expecting that we’re still trapped inside the captive portal browsers (I don’t have devices to test, though)

The following resources should be sufficient to show what needs to be implemented:
- https://github.com/httpwg/wiki/wiki/Captive-Portals
- https://serverfault.com/questions/679393/captive-portal-popups-the-definitive-guide#
-  https://msdn.microsoft.com/en-us/library/windows/hardware/dn408681.aspx

**Comment by kldavis4** [comment]
Tested on android and it thinks it is not connected and keeps asking to have the user login. It looks like for Android it is going to be somewhat involved, at least to cover a wide range of OS versions/variants. http://android.stackexchange.com/questions/123129/how-does-wifi-in-android-detect-if-the-device-has-to-sign-in-or-not

**Comment by edwinsteele** [comment]
Windows looks for `http://www.msftncsi.com/ncsi.txt` . The file has special contents, but an approach like Apple’s `success.html` should be sufficient.
[Microsoft doc](https://technet.microsoft.com/en-us/library/cc766017(v=ws.10).aspx) also mentions DNS, but only in the context of Vista. Given the MSDN reference is about Win 8, and doesn’t mention the DNS method, it’s probably safe to assume that the nsci.txt method is the only one necessary for current clients.

**Comment by edwinsteele** [comment]
Fixed by #69
