### ISSUE TITLE
Allow out-of-band reset to defaults

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#53]
If someone is locked out of the admin UI, there’s no way to get back in.

We need to allow triggering of a reset-to-defaults action if a particular file is present on the USB stick. The file should be automatically removed after the reset-to-defaults action. For ease of implementation, and to avoid having a periodic task, this action should only happen at boot time. i.e. one workflow would be:

1. yank power
2. unplug USB stick and create magic file (say, `_reset.txt` in the root of the USB stick),
3. re-insert USB stick
4. re-attach power

**Comment by kirkdwilson** [comment]
Good idea we will consider implementation.
