### ISSUE TITLE
Allow ssid, channel and hostname setting without admin UI

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#54]
Allow specification of the ssid, channel and hostname via txt files in the root of the USB stick. These files will be read and applied only at boot-time and the changes will be done via the same script that is used to perform actions on behalf of the admin interface. These config files should not be deleted, so they reapply on next reboot (unlike the reset file in #53)

**Comment by kirkdwilson** [comment]
Will these be available to change from the admin interface as well?  There really needs to be a way to change the SSID and channel number via the admin interface.

**Comment by edwinsteele** [comment]
Timing this out
