### ISSUE TITLE
Add popular content list to the front page

### ISSUE THREAD

**Issue by edwinsteele** [ConnectBox/connectbox-pi#59]
@GeoDirk requested that popular content is highlighted on the front page. This might be something like a top 10 popular files. This need not be accurate to the minute i.e. we can batch process the webserver logs and create a file that describes the top content.

**Comment by kldavis4** [comment]
Use log analyzer (visitor or goacess?) to compile stats to json which can be used for displaying popular content. I actually don't think either of those options can output to json, so we may need to roll our own...

**Comment by edwinsteele** [comment]
Completed in #128
