### ISSUE TITLE
Improve structure of client html

### ISSUE THREAD

**Issue by kldavis4** [ConnectBox/connectbox-pi#63]
Create build to combine and minify JS, CSS, etc
Have build pull in current version of font awesome css assets automatically (or a tag)

**Comment by edwinsteele** [comment]
@kldavis4 , do you still want to do this? Perhaps it's already done in your new client interface?

**Comment by kldavis4** [comment]
The react implementation does everything except automatically pull in the font awesome assets. If you think that's valuable, we can change this issue to just that.

**Comment by edwinsteele** [comment]
What we now have is sufficient. Thanks.
