### ISSUE TITLE
Keyboard Support

### ISSUE THREAD

**Issue by GeoDirk** [ConnectBox/connectbox-pi#93]
By default, the Raspberry Pi's are coming with keyboards configured for the UK.  It would enhance our configuration if the keyboard layout was defaulted to the 'US' layout.

All that needs to be done is modify the one line in /etc/default/keyboard to look like this:

XKBLAYOUT="us"

**Comment by edwinsteele** [comment]
@GeoDirk will probably have a go at this, when time permits. If it needs a fix before he can get to it, he'll let us know.

**Comment by GeoDirk** [comment]
Submitted push request...

**Comment by GeoDirk** [comment]
Code needs a bit of work...  Let me know what proper syntax is:

TASK [connectbox-pi : Set keyboard to the US layout] ***************************
fatal: [192.168.88.21]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: path"}

PLAY RECAP *********************************************************************
192.168.88.21              : ok=50   changed=38   unreachable=0    failed=1

**Comment by edwinsteele** [comment]
We decided not to proceed with this, as we’re not focussing on Raspbian.
